// Global layout (i.e. - page header, footer, main area, toolbars, sidebars, etc)

import type {Metadata} from 'next'
import '../styles/globals.css'
// import {QueryClient, QueryClientProvider} from '@tanstack/react-query'
import {ReactQueryProvider} from '@/lib/ReactQueryProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  )
}
